//Log in as GoshoGranatata
POST https://localhost:7034/Users/login
Content-Type: application/json

{"username": "GoshoGranatata", "password": "123123"}

###

GET https://localhost:7034/Comments/
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJKV1RTZXJ2aWNlQWNjZXNzVG9rZW4iLCJqdGkiOiJkYzMxMzYyMC0xNGJmLTQyODYtODM1MS1iOWQxMDMyOWZhNGUiLCJpYXQiOiIzMS8xMC8yMDIzIDE0OjEzOjI3IiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6Ikdvc2hvR3JhbmF0YXRhIiwiRW1haWwiOiJHb3Nob2dyYW5hdGF0YUBnbWFpbC5jb20iLCJJZCI6IjMiLCJleHAiOjE2OTg3NjUyMDcsImlzcyI6IkpXVEF1dGhlbnRpY2F0aW9uU2VydmVyIiwiYXVkIjoiSldUU2VydmljZUJsYXpvcldhc21DbGllbnQifQ.W8gwphisbATKPYpx05C_XZBi9ZQGOjlxaWWBtq9zCaD-FEx0K_KFQhzBq_L9TqavxP5P4eI8TY1C72mzXIIqIA